apiVersion: apps/v1
kind: Deployment
metadata:
  name: lawyerdesk-processo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lawyerdesk-processo
  template:
    metadata:
      labels:
        app: lawyerdesk-processo
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: lawyerdesk-processo-container
        image: lawyerdeskacr.azurecr.io/lawyerdeskacr-processo-repo:34
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: lawyerdesk-processo
spec:
  type: LoadBalancer
  ports:
  - port: 8082
  selector:
    app: lawyerdesk-processo